name = "nft-storage-dev"
type = "webpack"
account_id = "fffa4b4363a7e5250af8357087263b3a"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
    { binding = "SESSION", preview_id = "7916b9260aaa4900a6560ed0cb93e8b3" },
    { binding = "CSRF", preview_id = "3eadbc97ee754884bd693d0b31c57dc2" },
    { binding = "USERS", preview_id = "68553e93091e4f31b07ba21209ae98f9" },
    { binding = "NFTS", preview_id = "dff6dd60eb4a4956aab41c663a01aee9" }
]
vars = { AUTH0_CALLBACK_URL = "http://127.0.0.1:8787/auth", DEBUG = true }

[env.production]
name = "nft-storage"
vars = { AUTH0_CALLBACK_URL = "https://nft-storage.protocol-labs.workers.dev/auth", DEBUG = false }
kv_namespaces = [
    { binding = "USERS", id = "32c44d155e4a421eb9eec93f9dc4de18", preview_id = "68553e93091e4f31b07ba21209ae98f9" },
    { binding = "SESSION", id = "a4d1611719714028894895fd285a7980", preview_id = "7916b9260aaa4900a6560ed0cb93e8b3" },
    { binding = "USERS", id = "0989c8ffff4946c5b5964e8264966059", preview_id = "fb402ca278864e89bc8e82331f434b4e" },
    { binding = "NFTS", id = "58970be11a9c4a8baaaac1c16df552c3", preview_id = "dff6dd60eb4a4956aab41c663a01aee9" }
]

[site]
bucket = "./public"
entry-point = "."
