name: Client
on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/client/**'

jobs:
  check:
    name: Typecheck client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install

      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: client/tsconfig.json

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 16]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Test (ES)
        run: yarn --cwd packages/client test:es

      - name: Test (Web)
        run: yarn --cwd packages/client test:web

      - name: Test (CJS)
        run: yarn --cwd packages/client test:cjs

      - name: Coverage
        run: yarn --cwd packages/client coverage

  # publish:
  #   name: Publish client
  #   needs:
  #     - check
  #     - test
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cache node_modules
  #       id: cache-modules
  #       uses: actions/cache@v1
  #       with:
  #         path: node_modules
  #         key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
  #     - name: Install
  #       if: steps.cache-modules.outputs.cache-hit != 'true'
  #       run: yarn install
  #     - name: Build client
  #       run: yarn --cwd client build

  #     - name: Publish client
  #       uses: mikeal/merge-release@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  #         SRC_PACKAGE_DIR: client
  #         DEPLOY_DIR: client

  # docs:
  #   name: Generate documentation
  #   needs:
  #     - publish
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Cache node_modules
  #       id: cache-modules
  #       uses: actions/cache@v1
  #       with:
  #         path: node_modules
  #         key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

  #     - name: Install
  #       run: yarn install

  #     - name: Generate
  #       run: yarn build:client:docs

  #     - name: Commit
  #       uses: EndBug/add-and-commit@v7
  #       with:
  #         author_name: documentation-generator
  #         add: docs/client
  #         message: 'chore: generate client docs'
