name: Cron Pins

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    name: Update pin statuses and size
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run job
        env:
          DEBUG: '*'
          ENV: ${{ matrix.env }}
          CF_ACCOUNT: ${{ secrets.CF_ACCOUNT }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CLUSTER_API_URL: ${{ secrets.CLUSTER_API_URL }}
          CLUSTER_BASIC_AUTH_TOKEN: ${{ secrets.CLUSTER_BASIC_AUTH_TOKEN }}
          CLUSTER_IPFS_PROXY_API_URL: ${{ secrets.CLUSTER_IPFS_PROXY_API_URL }}
        run: yarn --cwd packages/cron start:pins
