name: Cron Pinata Sync

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Sync with Pinata
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - name: Run job
        env:
          DEBUG: '*'
          ENV: ${{ matrix.env }}
          CF_ACCOUNT: ${{ secrets.CF_ACCOUNT }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          PINATA_JWT: ${{ secrets.PINATA_JWT }}
        run: yarn --cwd packages/cron start:pinata
