on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <staging|production>'
        required: false
        default: ''
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Publish app
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ github.event.inputs.environment }}
