name: Website
on:
  push:
    branches:
      - main
    paths:
      - 'packages/website/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/website/**'

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: yarn test:website
